import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import { DM_Serif_Display } from "next/font/google";
import "./globals.scss";

const public_sans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-public-sans",
});
const dm_serif_display = DM_Serif_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-dm-serif-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${public_sans.variable} ${dm_serif_display.variable}`}>
      <body>{children}</body>
    </html>
  );
}
